Name = Kishan Kumar Rai

Email = kishan.rai99693@gmail.com

# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.


In [1]:
import numpy as np
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [5]:
lst1= []
lst2=[]

for i in range(5):
  a = int(input("Enter input for lst1 "))
  lst1.append(a)

for j in range(5):
  b = int(input("Enter input for lst2 "))
  lst2.append(b)

arr1 = np.array(lst1)
arr2 = np.array(lst2)

arr = np.concatenate((arr1, arr2))
print("The concatenate array is ", arr)

sort_arr = np.sort(arr)
print("The sorted array is ", sort_arr)


Enter input for lst1 1
Enter input for lst1 2
Enter input for lst1 3
Enter input for lst1 4
Enter input for lst1 5
Enter input for lst2 10
Enter input for lst2 9
Enter input for lst2 8
Enter input for lst2 7
Enter input for lst2 6
The concatenate array is  [ 1  2  3  4  5 10  9  8  7  6]
The sorted array is  [ 1  2  3  4  5  6  7  8  9 10]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size

In [8]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
print("The size of array is ", arr.size)
print("The dimension of array is ", arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The size of array is  9
The dimension of array is  2


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [20]:
arr = np.arange(11)
print("The array is ", arr)
print("The shape of 1D array is ", arr.shape)

arr1 = arr[np.newaxis, :]
print("The shape of 2D array w.r.t. row is ", arr1.shape)

arr2 = arr[:, np.newaxis]
print("The shape of 2D array w.r.t. column is ", arr2.shape)

arr3 = np.expand_dims(arr, 0)
print("The dimension of 2D array w.r.t. row is ", arr3.shape)

arr4 = np.expand_dims(arr, 1)
print("The dimension of 2D array w.r.t. column is ", arr4.shape)


The array is  [ 0  1  2  3  4  5  6  7  8  9 10]
The shape of 1D array is  (11,)
The shape of 2D array w.r.t. row is  (1, 11)
The shape of 2D array w.r.t. column is  (11, 1)
The dimension of 2D array w.r.t. row is  (1, 11)
The dimension of 2D array w.r.t. column is  (11, 1)


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [28]:
arr1 = np.square([1, 2, 3, 4, 5])
arr2 = np.square([6, 7, 8, 9, 10])

horizontal_arr = np.hstack((arr1, arr2))
print("The horizontally stack is ", horizontal_arr)

vertical_arr = np.vstack((arr1, arr2))
print("\nThe vertically stack is ", vertical_arr)

The horizontally stack is  [  1   4   9  16  25  36  49  64  81 100]

The vertically stack is  [[  1   4   9  16  25]
 [ 36  49  64  81 100]]


# Questions 6:
How to get unique items and counts of unique items?

In [29]:
arr = np.array([1,1,1,2,2,2,7,7,3,3,3,5,25,25,1,1,10,10,99])
unique, counts = np.unique(arr, return_counts=True)

arr1 = np.asarray((unique, counts)).T
print(arr1)

[[ 1  5]
 [ 2  3]
 [ 3  3]
 [ 5  1]
 [ 7  2]
 [10  2]
 [25  2]
 [99  1]]
